name: CI/CD - Microservices

on:
  workflow_dispatch:        # Lancement manuel
  pull_request:             # PR vers main
    branches: [main]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_API: api-gateway
  REPO_CLIENT: client-service
  REPO_ACCOUNT: account-service

jobs:

  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # ===== BUILD API-GATEWAY =====
      - name: Build API Gateway Image
        working-directory: ./api-gateway
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_API }}:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_API }}:latest

      # ===== BUILD CLIENT-SERVICE =====
      - name: Build Client Service Image
        working-directory: ./client-service
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_CLIENT }}:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_CLIENT }}:latest

      # ===== BUILD ACCOUNT-SERVICE =====
      - name: Build Account Service Image
        working-directory: ./account-service
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_ACCOUNT }}:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_ACCOUNT }}:latest


  deploy:
    name: Simulated Deployment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy all services
        run: echo "Simulating deployment of all services"
